### PR TITLE
Tc001 code has been completed, requesting permission to merge

### PR DESCRIPTION
**Pull request by aersin**
added awesome test case 1 automation code

### CODE REVIEW

**Review by aersin — COMMENTED** [review]
it needs some changes 
What kind of a change you mean?

**Review by Bahadir7706 — COMMENTED** [review]
Neresi done? olmamış bu.

**Review by aersin — COMMENTED** [review]
it not good enough

**Comment by aersin** [comment]
it is good to go

**Comment by Bahadir7706** [comment]
Firs merge is on the way

**Pull request merged**
